### ISSUE TITLE
I test tracer_x64.dll but it does not work as expected

### ISSUE THREAD

**Issue by Junch** [goldshtn/windbg-extensions#1]
bp ntdll!RtlAllocateHeap "r $t0 = @r8; gu; .printf \"A %p\n\", @rax; gc"
bp ntdll!RtlFreeHeap ".printf \"F %p\n\", @r8; gc"

I find that one heap may be free multiple times.
...
A 000000000043be00
A 000000000043bf90
F 000000000043bf90
F 000000000043bf90
F 000000000043bd40
...

**Comment by goldshtn** [comment]
It's not an issue with the tracer extension. In fact, you are not even using the tracer extension in the example you pasted above: you are just using WinDbg breakpoints.
